# Generated by Django 4.2.1 on 2023-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceassignment',
            name='device_condition_when_assigned',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='device_condition_when_returned',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
