# Generated by Django 4.2.1 on 2023-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='company_logo/')),
                ('establish_date', models.DateField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=400)),
            ],
        ),
    ]
